version: '3.8'
services:
  expo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental-expo-dev
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.11.108  # Replace with your actual IP
      # Firebase configuration (use env variables)
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
    ports:
      - "19000:19000" # Expo app
      - "19001:19001" # Metro bundler
      - "19002:19002" # Expo developer tools
      - "19006:19006" # Expo web (if using)
      - "8082:8081"   # React Native packager
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - expo-cache:/root/.expo
    stdin_open: true # -i
    tty: true        # -t
    command: npx expo start --clear --lan
  # Optional: Add a web service to easily view i18n files
  i18n-viewer:
    image: nginx:alpine
    container_name: car-rental-i18n-viewer
    ports:
      - "8080:80"
    volumes:
      - ./app/i18n/locales:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - expo-app
volumes:
  node_modules:
  expo-cache: